supported_symbols = {
    "1INCH": ["KRW", "BTC"],
    "AAVE": ["KRW", "BTC"],
    "ADA": ["KRW", "BTC", "USDT"],
    "ALGO": ["KRW", "BTC"],
    "ANKR": ["KRW", "BTC"],
    "ATOM": ["KRW", "BTC"],
    "AVAX": ["KRW", "BTC"],
    "BAT": ["KRW", "BTC", "USDT"],
    "BCH": ["KRW", "BTC", "USDT"],
    "BNT": ["BTC"],
    "BTC": ["USDT"],  # TODO Doesn't matter how many krw btc is
    "COMP": ["BTC"],
    "CRV": ["BTC"],
    "DAI": ["BTC"],
    "DOGE": ["KRW", "BTC", "USDT"],
    "DOT": ["KRW", "BTC"],
    "EOS": ["KRW", "BTC"],
    "ETC": ["KRW", "BTC", "USDT"],
    "ETH": ["KRW", "BTC", "USDT"],
    "FIL": ["BTC"],
    "KNC": ["KRW"],
    "LINK": ["BTC", "KRW"],
    "LRC": ["BTC"],
    "MATIC": ["KRW", "BTC"],
    "MKR": ["BTC"],
    "NEAR": ["KRW", "BTC"],
    "ONT": ["KRW"],
    "REP": ["KRW", "BTC"],
    "SOL": ["KRW", "BTC"],
    "TRX": ["KRW", "BTC", "USDT"],
    "TUSD": ["BTC", "USDT"],
    "UNI": ["BTC"],
    "USDT": [],
    "VET": "vechain",
    "XLM": ["BTC", "KRW"],
    "XRP": ["KRW", "BTC", "USDT"],
    "XTZ": ["BTC", "KRW"],
    "ZRX": ["KRW", "BTC", "USDT"],
    "BFC": ["BTC"]
}
