BIFROST_VALIDATOR_HISTORY_LIMIT_BLOCKS = 6
BOOTSTRAP_OFFSET_ROUNDS = 5

RBC_EVENT_STATUS_START_DATA_START_INDEX = 128
RBC_EVENT_STATUS_START_DATA_END_INDEX = 160

SOCKET_CONTRACT_NAME = "socket"
SUBMIT_FUNCTION_NAME = "poll"
GET_REQ_INFO_FUNCTION_NAME = "get_request"
ROUND_UP_VOTING_FUNCTION_NAME = "round_control_relay"
AUTHORITY_CONTRACT_NAME = "authority"
RELAYER_AUTHORITY_CONTRACT_NAME = "relayer_authority"
GET_ROUND_FUNCTION_NAME = "latest_round"
